runtime: nodejs10
service: main
handlers:
  - url: /
    build_files: build/index.html
    upload: build/index.html
    secure: always
    expiration: 1s
  - url: /
    expiration: 1s
    build_dir: build
    secure: always

default_expiration: 1s
