runtime: nodejs10
service: main
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    expiration: 1s
  - url: /
    expiration: 10m
    static_dir: build
    secure: always

default_expiration: 10m
